### ISSUE TITLE
Better error for creating a file in the home directory

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder_jupyter#22]
A Girder collection or home folder cannot contain items, so if you try to e.g. create a notebook when in the home directory, you get "Error Invalid response: 404 Not Found". A better error would be great here, especially because this is the default location when starting up jupyter lab. New users like me are likely to be bitten by this often.

BTW I tried it using the blog post instructions and it just works otherwise. Very cool! 🎉

**Comment by cjh1** [comment]
@jeffbaumes Thanks for reporting this. Can you try uploading a regular file? I added a better error message for this case. I guess I didn't realize they were different code paths.

**Comment by cjh1** [comment]
Fixed by #25
